### ISSUE TITLE
comrak does not compile on rustc 1.26.0-night

### ISSUE THREAD

**Issue by technetos** [kivikakk/comrak#54]
```
error[E0518]: attribute should be applied to function
 --> /home/username/.cargo/registry/src/github.com-1ecc6299db9ec823/comrak-0.2.8/src/scanners.rs:8:10
  |
8 | #[derive(Parser)]
  |          ^^^^^^ not a function

error: aborting due to previous error

For more information about this error, try `rustc --explain E0518`.
error: Could not compile `comrak`.
```

**Comment by kivikakk** [comment]
Interesting! I'll look into it, thanks.

**Comment by kivikakk** [comment]
The explain describes:

```
This error indicates that an `#[inline(..)]` attribute was incorrectly placed
on something other than a function or method.

Examples of erroneous code:

```
#[inline(always)]
struct Foo;

#[inline(never)]
impl Foo {
    // ...
}
```

`#[inline]` hints the compiler whether or not to attempt to inline a method or
function. By default, the compiler does a pretty good job of figuring this out
itself, but if you feel the need for annotations, `#[inline(always)]` and
`#[inline(never)]` can override or force the compiler's decision.

If you wish to apply this attribute to all methods in an impl, manually annotate
each method; it is not possible to annotate the entire impl with an `#[inline]`
attribute.
```

It suggests the error is happening in proc_macro-generated code (i.e. in `pest`). I'll investigate and report upstream.

**Comment by kivikakk** [comment]
=> pest-parser/pest#218

**Comment by technetos** [comment]
Everything works on my end now :smile: 

Thankyou so much for getting the problem resolved, your awesome :heart:

**Comment by kivikakk** [comment]
Thanks so much for the report, I'd have had no idea otherwise! 😸 :heart:
