### ISSUE TITLE
Latest releases lost support for Rust stable

### ISSUE THREAD

**Issue by alerque** [kivikakk/comrak#151]
From the readme:

> Comrak supports Rust stable.

This is not true of the latest rush of releases (0.7.1, 0.8.0, or 0.8.1). Here is the Clippy error:

```console
error[E0554]: `#![feature]` may not be used on the stable release channel
  --> src/lib.rs:74:37
   |
74 | #![cfg_attr(feature = "benchmarks", feature(test))]
   |                                     ^^^^^^^^^^^^^
```

Rustup informs me I'm running:

    stable-x86_64-unknown-linux-gnu unchanged - rustc 1.45.2 (d3fb005a3 2020-07-31)

Please either fix this so stable Rust can be used again or change the documentation to reflect the actual state of affairs (and maybe add a note about the change in the release notes for the sake of package builders).

**Comment by kivikakk** [comment]
Thanks for opening the issue!

This should only happen if building with `--features benchmarks` — this code has been unchanged since 0.2.9.  Can you check that you haven't enabled building with `--all-features` (or similar) recently?  The only required features are `clap` for the binary; none needed for just the library.

**Comment by alerque** [comment]
Yes, I'm using `--all-features` which is standard procedure for packaging Rust projects on Arch Linux. But here's the thing: This worked on 0.7.0 using Rust stable:

https://aur.archlinux.org/cgit/aur.git/commit/?h=comrak&id=8deab76c57aaa3f608ea170160a124a64221f58a

I've changed the packaging for newer versions to use `--feature clap`, but I think the Cargo.toml file is probably missing something. I'm not quite sure what but either benchmarks should be a dev-only dependency or it should call out the version of Rust that it needs or something.

**Comment by kivikakk** [comment]
This is strange. I get the failure locally when I check out `0.7.0` and build using the same command; I wonder how this has happened.

Anyway, I'll fix this up so it works on stable either way. Thanks for bringing this to my attention, will update this issue when done.
